suppressPackageStartupMessages({ library(readr); library(dplyr) })
ref <- read_csv("app/species_accepted.csv", show_col_types = FALSE)
cat("=== germanica matches ===\n")
print(ref |> filter(grepl("germanica", taxon_name, ignore.case = TRUE)) |> select(taxon_name) |> head(30))
cat("=== Iris × / Iris hybrid ===\n")
print(ref |> filter(grepl("^Iris ", taxon_name)) |> select(taxon_name) |> head(40))
cat("=== Leucanthemum ===\n")
print(ref |> filter(grepl("Leucanthemum", taxon_name)) |> select(taxon_name) |> head(40))
cat("=== Heucherella ===\n")
print(ref |> filter(grepl("eucherella", taxon_name, ignore.case = TRUE)) |> select(taxon_name) |> head(20))
cat("=== Leucanthemum × superbum ===\n")
print(ref |> filter(grepl("superbum", taxon_name, ignore.case = TRUE)) |> select(taxon_name) |> head(20))
cat("=== Tiarella ===\n")
print(ref |> filter(grepl("Tiarella ", taxon_name)) |> select(taxon_name) |> head(20))
cat("=== Leucanthemum maximum / lacustre ===\n")
print(ref |> filter(grepl("Leucanthemum (maximum|lacustre|vulgare)", taxon_name)) |> select(taxon_name))
